### ISSUE TITLE
How to Deploy?

### ISSUE THREAD

**Issue by DragAditya** [sachinsenal0x64/MULTI-GPT#26]
Please Bro

**Comment by sachinsenal0x64** [comment]
Hello there I simply changed the topic name into English and don't know your language. You must be asking how to properly set up the application. So let's start with the easy part. After filling in the keys, rename **.env.example** to **.env** You will need a chat GPT account and its token, which you can obtain from the browser's inspect.

**Comment by sachinsenal0x64** [comment]
I hope you fix the problem so I'm going to close.

**Comment by DragAditya** [comment]
Thanks 👍😊
