### ISSUE TITLE
How to Get dalle 2 big image ai cookies

### ISSUE THREAD

**Issue by DragAditya** [sachinsenal0x64/MULTI-GPT#35]
???

**Comment by sachinsenal0x64** [comment]
it's by default have Dalle 2 with /img command btw you also can use Bing Dalle with /art if you want to setup [Read This](https://github.com/sachinsenal0x64/MULTI-GPT/issues/26#issuecomment-1650076761)

**Comment by sachinsenal0x64** [comment]
i hope you fix :)
