### ISSUE TITLE
bot doesn't respond

### ISSUE THREAD

**Issue by MrFadzay** [sachinsenal0x64/MULTI-GPT#38]
the code runs without errors, the bot is online.  but there is no response in telegrams, any commands remain unanswered.  Everything in the .env file is correct

**Comment by sachinsenal0x64** [comment]
are you using replit ?

**Comment by MrFadzay** [comment]
> are you using replit ?

Yes I'm deploy repo in replit, but I tried running this on local computer and same problem. and your bot, which is also not working for testing on the main page https://t.me/OPENAIX_BOT

**Comment by sachinsenal0x64** [comment]
yes demo bot was down i will check this again

**Comment by sachinsenal0x64** [comment]
> the code runs without errors, the bot is online. but there is no response in telegrams, any commands remain unanswered. Everything in the .env file is correct

hey bot working fine you should check "HOST_URL ENV"

![Screenshot_20231007_235021](https://github.com/sachinsenal0x64/MULTI-GPT/assets/127573781/940facd0-5c56-45bd-900e-ddc28fb44871)

demo bot = https://t.me/testgptx_bot
